### ISSUE TITLE
Dropped EtherCAT packets shouldn't show up in topics

### ISSUE THREAD

**Issue by Rocketmagnet** [shadow-robot/sr-ronex#30] opened 2013-08-05 12:40 UTC
Connect some analogue sensors to a Ronex, and use rostopic echo to watch the analogue topic.

Occasionally one message appears which has all analogue readings at zero. This is due to a missed packet, caused by jitter in the 'realtime' loop. The host needs to detect these and filter them out.

Ideally, this would be done the same way it's done in the EDC Palms. There is a command_type word which is sent in the EtherCAT command struct. The command_word in the status struct should match this. If it doesn't, or it's zero, then the packet is bad.

Unfortunately, we seem to have commented this out in the .h file. We need to put this back in, both in the driver and the firmware.

**Comment by toliver** [comment] 2013-09-16 16:49
The problem is not exactly that we drop packages, but that we are using the EC_QUEUED protocol to read the status from the ronex module, and the jitter sometimes causes that we read too soon, before the data has actually been written into the memory,

Just had a chat with Hugo about this, and there are a few options:
- Uncomment the command_word field in the .h and in the driver seems to be the best solution technically, but it would make the driver incompatible with the ronex Mk2 that have been sent to one of the Stiff-flop partners.
- We could use some ugly trickery to detect if a frame is full of zeros (which is a valid status by itself) but the previous frame/s wasn't. This would mean that is an invalid frame. Dirty.
- Define a  new product_id for the ronex Mk3 and add the solution in the first point. This would keep the Mk2 we've delivered compatible with the driver, but we would have a duplicated driver with only minor differences, and the Mk2 would still have the problem of the zero readings unsolved.

**Comment by toliver** [comment] 2013-09-16 17:03
As Mark points out, we shouldn't worry about stiff-flop as it's a separate code base.

We can fix it the right way for ronex. and later on decide on how do we do it for stiff-flop.

**Comment by ugocupcic** [comment] 2013-09-16 19:27
Cool. This means slightly new firmware as well? If it's the case, make sure
Thiago knows about this before developing.

On 16 September 2013 19:03, toliver notifications@github.com wrote:

> As Mark points out, we shouldn't worry about stiff-flop as it's a separate
> code base.
> 
> We can fix it the right way for ronex. and later on decide on how do we do
> it for stiff-flop.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/30#issuecomment-24526317
> .

## 

Ugo Cupcic _Senior Software Engineer_+44 20 7700 2487ugo@shadowrobot.com
www.shadowrobot.com

## 

---

_Shadow Robot Company Ltd._
251 Liverpool Road, N1 1LX, UK

## Registered Number 3308007 (England & Wales)

**Comment by ugocupcic** [comment] 2013-09-19 05:58
Toni are you working on this? Had the OK from @ta-shadow yesterday.

**Comment by toliver** [comment] 2013-09-19 07:42
Yes. It's finished pending testing with reprogrammed HW. In a branch I
pushed yesterday.
We should wait to merge this until everything else is working, as your
ronex will be incompatible.

Toni are you working on this? Had the OK from
@ta-shadowhttps://github.com/ta-shadowyesterday.

—
Reply to this email directly or view it on
GitHubhttps://github.com/shadow-robot/sr-ronex-dev/issues/30#issuecomment-24718672
.

**Comment by ugocupcic** [comment] 2013-09-19 07:44
Nice!

Yes I hope we can reprogram my ronex. Do you have a link to the programmer I'd need?

**Comment by toliver** [comment] 2013-09-19 07:47
No. We will have to ask Hugo.

**Comment by toliver** [comment] 2013-09-20 11:36
Tested and working.
Checked again the bad behaviour with the older protocol and checked that it's solved by checking the command_type field in the received status frame.

**Closed as completed** 2013-09-20 13:27 UTC
